development:
  # Configure available database clients. (required)
  clients:
    # Defines the default client. (required)
    default:
      # Defines the name of the default database that Mongoid can connect to.
      # (required).
      database: book_info_development
      # Provides the hosts the default client can connect to. Must be an array
      # of host:port pairs. (required)
      hosts:
        - db:27017
      options:
        # The name of the user for authentication.
        user: "root"
        # The password of the user for authentication.
        password: "example"
        # The user's database roles.
        roles:
          - 'dbOwner'
        # Change the default authentication mechanism. Valid options are: :scram,
        # :mongodb_cr, :mongodb_x509, and :plain. (default on 3.0 is :scram, default
        # on 2.4 and 2.6 is :plain)
        # auth_mech: :scram
        # The database or source to authenticate the user against. (default: admin)
        auth_source: admin
test:
  clients:
    default:
      database: book_info_test
      hosts:
        - db:27017
      options:
        # The name of the user for authentication.
        user: "root"
        # The password of the user for authentication.
        password: "example"
        # The user's database roles.
        roles:
          - 'dbOwner'
        # Change the default authentication mechanism. Valid options are: :scram,
        # :mongodb_cr, :mongodb_x509, and :plain. (default on 3.0 is :scram, default
        # on 2.4 and 2.6 is :plain)
        # auth_mech: :scram
        # The database or source to authenticate the user against. (default: admin)
        auth_source: admin